use_frameworks!

target 'KissPaginate_Example' do
  pod 'KissPaginate', :path => '../'

  target 'KissPaginate_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.9.3'
  pod 'Nimble', '~> 4.1.0'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end
end
