# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- cd Example
- pod install
- xcodebuild clean -workspace KissPaginate.xcworkspace -scheme "KissPaginate-Example" | xcpretty
- xcodebuild test -workspace KissPaginate.xcworkspace -scheme "KissPaginate-Example" -sdk 'iphonesimulator10.0' -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0' build test
after_success:
    - bash <(curl -s https://codecov.io/bash)
